name: surprisenet
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
    - mido
    - matplotlib
    - music21
    - numpy
    - pretty-midi
    - scipy
    - pypianoroll==0.5.3 
    - torch
    - torchvision
    - tqdm
    - matplotlib
    - requests
    - bs4
    - xmltodict
    - lxml